id: I8B866625
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:35:16+00:00'
last_modified: '2022-06-07T20:26:00.337167+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74178
  title: གསང་བ་འདུས་པའི་གནད་དོན་གསལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DF8B:
      image_group_id: I4CZ74227
      title: ''
      total_pages: 646
      order: 1
      base_file: DF8B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
