id: P004127
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ74178
  title: གསང་བ་འདུས་པའི་གནད་དོན་གསལ་བ།
  author: ''
  volumes:
    d2383a86074047e9a75b23b06a2bc306:
      image_group_id: I4CZ74227
      title: ''
      volume_number: 1
      total_pages: 646
      base_file: v001.txt
